import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist",
      // Build scratch directories written by scripts/storage-test.mjs and
      // scripts/retention-live-test.mjs. Compiled output, never edited.
      ".storage",
      ".retention",
      /*
       * Vendored shadcn/ui primitives. These are generated by the shadcn CLI and
       * are meant to be re-generated, so hand-fixing the two rules they trip
       * (empty interfaces that exist to name a prop type, and files exporting a
       * cva variant next to a component) buys nothing: the next `shadcn add`
       * puts it straight back. Our own code is linted with no exemptions.
       */
      "src/components/ui/**",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // Node scripts and config files: Node globals, not browser ones.
    files: ["scripts/**/*.{js,mjs}", "*.config.{ts,js}"],
    languageOptions: { globals: globals.node },
  },
);
