export interface PDFTemplate {
  id: string;
  name: string;
  description: string;
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    text: string;
  };
  fonts: {
    heading: string;
    body: string;
  };
  layout: 'minimal' | 'modern' | 'classic' | 'bold' | 'elegant';
  preview: string;
}

export interface DocumentSection {
  id: string;
  title: string;
  content: string;
}

export const languages = [
  { code: 'auto', name: 'Auto Detect', native: '🌐 Auto' },
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिंदी' },
  { code: 'hi-en', name: 'Hinglish', native: 'Hinglish (हिंदी + English)' },
  { code: 'es', name: 'Spanish', native: 'Español' },
  { code: 'fr', name: 'French', native: 'Français' },
  { code: 'de', name: 'German', native: 'Deutsch' },
  { code: 'zh', name: 'Chinese', native: '中文' },
  { code: 'ja', name: 'Japanese', native: '日本語' },
  { code: 'ko', name: 'Korean', native: '한국어' },
  { code: 'ar', name: 'Arabic', native: 'العربية' },
  { code: 'ru', name: 'Russian', native: 'Русский' },
  { code: 'pt', name: 'Portuguese', native: 'Português' },
  { code: 'it', name: 'Italian', native: 'Italiano' },
  { code: 'nl', name: 'Dutch', native: 'Nederlands' },
  { code: 'tr', name: 'Turkish', native: 'Türkçe' },
  { code: 'pl', name: 'Polish', native: 'Polski' },
  { code: 'sv', name: 'Swedish', native: 'Svenska' },
  { code: 'no', name: 'Norwegian', native: 'Norsk' },
  { code: 'da', name: 'Danish', native: 'Dansk' },
  { code: 'fi', name: 'Finnish', native: 'Suomi' },
  { code: 'th', name: 'Thai', native: 'ไทย' },
  { code: 'vi', name: 'Vietnamese', native: 'Tiếng Việt' },
  { code: 'id', name: 'Indonesian', native: 'Bahasa Indonesia' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'ur', name: 'Urdu', native: 'اردو' },
  { code: 'ne', name: 'Nepali', native: 'नेपाली' },
  { code: 'si', name: 'Sinhala', native: 'සිංහල' },
  { code: 'my', name: 'Burmese', native: 'မြန်မာ' },
  { code: 'km', name: 'Khmer', native: 'ខ្មែរ' },
  { code: 'lo', name: 'Lao', native: 'ລາວ' },
  { code: 'ka', name: 'Georgian', native: 'ქართული' },
  { code: 'hy', name: 'Armenian', native: 'Հայերեն' },
  { code: 'am', name: 'Amharic', native: 'አማርኛ' },
  { code: 'sw', name: 'Swahili', native: 'Kiswahili' },
  { code: 'yo', name: 'Yoruba', native: 'Yorùbá' },
  { code: 'ha', name: 'Hausa', native: 'Hausa' },
  { code: 'zu', name: 'Zulu', native: 'isiZulu' },
  { code: 'ms', name: 'Malay', native: 'Bahasa Melayu' },
  { code: 'tl', name: 'Filipino', native: 'Filipino' },
  { code: 'uk', name: 'Ukrainian', native: 'Українська' },
  { code: 'cs', name: 'Czech', native: 'Čeština' },
  { code: 'ro', name: 'Romanian', native: 'Română' },
  { code: 'hu', name: 'Hungarian', native: 'Magyar' },
  { code: 'el', name: 'Greek', native: 'Ελληνικά' },
  { code: 'he', name: 'Hebrew', native: 'עברית' },
  { code: 'fa', name: 'Persian', native: 'فارسی' },
  { code: 'ca', name: 'Catalan', native: 'Català' },
  { code: 'eu', name: 'Basque', native: 'Euskara' },
  { code: 'gl', name: 'Galician', native: 'Galego' },
  { code: 'cy', name: 'Welsh', native: 'Cymraeg' },
  { code: 'ga', name: 'Irish', native: 'Gaeilge' },
  { code: 'gd', name: 'Scottish Gaelic', native: 'Gàidhlig' },
  { code: 'is', name: 'Icelandic', native: 'Íslenska' },
  { code: 'et', name: 'Estonian', native: 'Eesti' },
  { code: 'lv', name: 'Latvian', native: 'Latviešu' },
  { code: 'lt', name: 'Lithuanian', native: 'Lietuvių' },
  { code: 'sr', name: 'Serbian', native: 'Српски' },
  { code: 'hr', name: 'Croatian', native: 'Hrvatski' },
  { code: 'bg', name: 'Bulgarian', native: 'Български' },
  { code: 'sk', name: 'Slovak', native: 'Slovenčina' },
  { code: 'sl', name: 'Slovenian', native: 'Slovenščina' },
  { code: 'uz', name: 'Uzbek', native: 'Oʻzbek' },
  { code: 'kk', name: 'Kazakh', native: 'Қазақ' },
  { code: 'az', name: 'Azerbaijani', native: 'Azərbaycan' },
  { code: 'mi', name: 'Maori', native: 'Te Reo Māori' },
] as const;

export const pageSizes = [
  { id: 'A4', label: 'A4 (210 × 297 mm)', width: 210, height: 297 },
  { id: 'Letter', label: 'Letter (8.5 × 11 in)', width: 215.9, height: 279.4 },
  { id: 'Legal', label: 'Legal (8.5 × 14 in)', width: 215.9, height: 355.6 },
  { id: 'Tabloid', label: 'Tabloid (11 × 17 in)', width: 279.4, height: 431.8 },
  { id: 'A3', label: 'A3 (297 × 420 mm)', width: 297, height: 420 },
  { id: 'A5', label: 'A5 (148 × 210 mm)', width: 148, height: 210 },
  { id: 'B5', label: 'B5 (176 × 250 mm)', width: 176, height: 250 },
  { id: 'Executive', label: 'Executive (7.25 × 10.5 in)', width: 184.15, height: 266.7 },
  { id: 'Square', label: 'Square (210 × 210 mm)', width: 210, height: 210 },
  { id: 'Reel', label: 'Reel / Story 9:16 (1080 × 1920)', width: 108, height: 192 },
  { id: 'Presentation', label: 'Presentation 16:9', width: 254, height: 142.9 },
] as const;

export const pdfTemplates: PDFTemplate[] = [
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean and simple design',
    colors: {
      primary: '#000000',
      secondary: '#666666',
      accent: '#999999',
      background: '#FFFFFF',
      text: '#222222',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'minimal',
    preview: '📄',
  },
  {
    id: 'professional',
    name: 'Professional',
    description: 'Corporate and polished',
    colors: {
      primary: '#1E3A8A',
      secondary: '#3B82F6',
      accent: '#60A5FA',
      background: '#FFFFFF',
      text: '#1F2937',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'modern',
    preview: '💼',
  },
  {
    id: 'creative',
    name: 'Creative',
    description: 'Bold and artistic',
    colors: {
      primary: '#EC4899',
      secondary: '#F472B6',
      accent: '#FBBF24',
      background: '#FEF3C7',
      text: '#831843',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'bold',
    preview: '🎨',
  },
  {
    id: 'modern',
    name: 'Modern',
    description: 'Contemporary and sleek',
    colors: {
      primary: '#6366F1',
      secondary: '#8B5CF6',
      accent: '#A78BFA',
      background: '#F9FAFB',
      text: '#111827',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'modern',
    preview: '✨',
  },
  {
    id: 'classic',
    name: 'Classic',
    description: 'Timeless and elegant',
    colors: {
      primary: '#92400E',
      secondary: '#D97706',
      accent: '#FBBF24',
      background: '#FFFBEB',
      text: '#451A03',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    preview: '📚',
  },
  {
    id: 'elegant',
    name: 'Elegant',
    description: 'Sophisticated and refined',
    colors: {
      primary: '#7C3AED',
      secondary: '#A78BFA',
      accent: '#C4B5FD',
      background: '#FFFFFF',
      text: '#4C1D95',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'elegant',
    preview: '👔',
  },
  {
    id: 'bold',
    name: 'Bold',
    description: 'Strong and impactful',
    colors: {
      primary: '#DC2626',
      secondary: '#EF4444',
      accent: '#F87171',
      background: '#FEF2F2',
      text: '#7F1D1D',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'bold',
    preview: '⚡',
  },
  {
    id: 'tech',
    name: 'Tech',
    description: 'Digital and futuristic',
    colors: {
      primary: '#0891B2',
      secondary: '#06B6D4',
      accent: '#22D3EE',
      background: '#ECFEFF',
      text: '#164E63',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'modern',
    preview: '💻',
  },
  {
    id: 'academic',
    name: 'Academic',
    description: 'Scholarly and formal',
    colors: {
      primary: '#1E40AF',
      secondary: '#3B82F6',
      accent: '#93C5FD',
      background: '#FFFFFF',
      text: '#1E3A8A',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    preview: '🎓',
  },
  {
    id: 'corporate',
    name: 'Corporate',
    description: 'Business and professional',
    colors: {
      primary: '#374151',
      secondary: '#6B7280',
      accent: '#9CA3AF',
      background: '#F9FAFB',
      text: '#111827',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'modern',
    preview: '🏢',
  },
  {
    id: 'artistic',
    name: 'Artistic',
    description: 'Creative and expressive',
    colors: {
      primary: '#DB2777',
      secondary: '#EC4899',
      accent: '#F472B6',
      background: '#FDF2F8',
      text: '#831843',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'bold',
    preview: '🖼️',
  },
  {
    id: 'clean',
    name: 'Clean',
    description: 'Simple and clear',
    colors: {
      primary: '#059669',
      secondary: '#10B981',
      accent: '#34D399',
      background: '#FFFFFF',
      text: '#064E3B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'minimal',
    preview: '🌿',
  },
  {
    id: 'vibrant',
    name: 'Vibrant',
    description: 'Colorful and energetic',
    colors: {
      primary: '#EA580C',
      secondary: '#F97316',
      accent: '#FB923C',
      background: '#FFF7ED',
      text: '#7C2D12',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'bold',
    preview: '🌈',
  },
  {
    id: 'dark',
    name: 'Dark',
    description: 'Modern dark theme',
    colors: {
      primary: '#F3F4F6',
      secondary: '#D1D5DB',
      accent: '#9CA3AF',
      background: '#1F2937',
      text: '#F9FAFB',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'modern',
    preview: '🌙',
  },
  {
    id: 'light',
    name: 'Light',
    description: 'Bright and airy',
    colors: {
      primary: '#4B5563',
      secondary: '#6B7280',
      accent: '#9CA3AF',
      background: '#FFFFFF',
      text: '#374151',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'minimal',
    preview: '☀️',
  },
];
